#pragma once
#include <iostream>
#include "stack1.hpp"
#include <vector>
#include <string>
#include <chrono>
#include <unordered_map>
#include <map>
#include <bitset>
#include "Templates.hpp"
#include <deque>
#include <algorithm>
#include <type_traits>
#include "person.hpp"
#include  <functional>
#include <utility>
#include <list>
#include "MyArray.hpp"
#include <valarray>
#include "Array.hpp"